
TABS = (TAB_MODLIST, TAB_FILETREE, TAB_INSTALLER) = list(range(3))

# COLUMNS = (COL_NUMBER, COL_ENABLED, COL_MODID, COL_VERSION, COL_NAME) = list(range(4))

# combine order-number and checkbox
COLUMNS = (COL_ENABLED, COL_MODID, COL_VERSION, COL_NAME) = list(range(4))

DBLCLICK_COLS = [COL_ENABLED, COL_MODID, COL_VERSION]





