# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skymodman/interface/designer/ui/preferences.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(600, 400)
        self.gridLayout = QtWidgets.QGridLayout(Preferences)
        self.gridLayout.setObjectName("gridLayout")
        self.prefs_tabwidget = QtWidgets.QTabWidget(Preferences)
        self.prefs_tabwidget.setObjectName("prefs_tabwidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_general)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbox_startup = QtWidgets.QGroupBox(self.tab_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbox_startup.sizePolicy().hasHeightForWidth())
        self.gbox_startup.setSizePolicy(sizePolicy)
        self.gbox_startup.setObjectName("gbox_startup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbox_startup)
        self.verticalLayout_2.setContentsMargins(50, -1, -1, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbox_loadlastprofile = QtWidgets.QCheckBox(self.gbox_startup)
        self.cbox_loadlastprofile.setChecked(True)
        self.cbox_loadlastprofile.setObjectName("cbox_loadlastprofile")
        self.verticalLayout_2.addWidget(self.cbox_loadlastprofile)
        self.verticalLayout.addWidget(self.gbox_startup)
        self.gbox_paths = QtWidgets.QGroupBox(self.tab_general)
        self.gbox_paths.setObjectName("gbox_paths")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbox_paths)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_choosedir_skyrim = QtWidgets.QToolButton(self.gbox_paths)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_choosedir_skyrim.setIcon(icon)
        self.btn_choosedir_skyrim.setObjectName("btn_choosedir_skyrim")
        self.gridLayout_2.addWidget(self.btn_choosedir_skyrim, 0, 2, 1, 1)
        self.le_dirskyrim = QtWidgets.QLineEdit(self.gbox_paths)
        self.le_dirskyrim.setReadOnly(True)
        self.le_dirskyrim.setObjectName("le_dirskyrim")
        self.gridLayout_2.addWidget(self.le_dirskyrim, 0, 1, 1, 1)
        self.le_dirmods = QtWidgets.QLineEdit(self.gbox_paths)
        self.le_dirmods.setReadOnly(True)
        self.le_dirmods.setObjectName("le_dirmods")
        self.gridLayout_2.addWidget(self.le_dirmods, 1, 1, 1, 1)
        self.lbl_skyrim = QtWidgets.QLabel(self.gbox_paths)
        self.lbl_skyrim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_skyrim.setObjectName("lbl_skyrim")
        self.gridLayout_2.addWidget(self.lbl_skyrim, 0, 0, 1, 1)
        self.btn_choosedir_mods = QtWidgets.QToolButton(self.gbox_paths)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_choosedir_mods.setIcon(icon)
        self.btn_choosedir_mods.setObjectName("btn_choosedir_mods")
        self.gridLayout_2.addWidget(self.btn_choosedir_mods, 1, 2, 1, 1)
        self.lbl_mods = QtWidgets.QLabel(self.gbox_paths)
        self.lbl_mods.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mods.setObjectName("lbl_mods")
        self.gridLayout_2.addWidget(self.lbl_mods, 1, 0, 1, 1)
        self.lbl_vfs = QtWidgets.QLabel(self.gbox_paths)
        self.lbl_vfs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_vfs.setObjectName("lbl_vfs")
        self.gridLayout_2.addWidget(self.lbl_vfs, 2, 0, 1, 1)
        self.le_dirvfs = QtWidgets.QLineEdit(self.gbox_paths)
        self.le_dirvfs.setReadOnly(True)
        self.le_dirvfs.setObjectName("le_dirvfs")
        self.gridLayout_2.addWidget(self.le_dirvfs, 2, 1, 1, 1)
        self.btn_choosedir_vfs = QtWidgets.QToolButton(self.gbox_paths)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_choosedir_vfs.setIcon(icon)
        self.btn_choosedir_vfs.setObjectName("btn_choosedir_vfs")
        self.gridLayout_2.addWidget(self.btn_choosedir_vfs, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.gbox_paths)
        self.prefs_tabwidget.addTab(self.tab_general, "")
        self.tab_paths = QtWidgets.QWidget()
        self.tab_paths.setObjectName("tab_paths")
        self.prefs_tabwidget.addTab(self.tab_paths, "")
        self.tab_profiles = QtWidgets.QWidget()
        self.tab_profiles.setObjectName("tab_profiles")
        self.prefs_tabwidget.addTab(self.tab_profiles, "")
        self.gridLayout.addWidget(self.prefs_tabwidget, 0, 0, 1, 1)
        self.prefs_btnbox = QtWidgets.QDialogButtonBox(Preferences)
        self.prefs_btnbox.setOrientation(QtCore.Qt.Horizontal)
        self.prefs_btnbox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.prefs_btnbox.setObjectName("prefs_btnbox")
        self.gridLayout.addWidget(self.prefs_btnbox, 1, 0, 1, 1)

        self.retranslateUi(Preferences)
        self.prefs_tabwidget.setCurrentIndex(0)
        self.prefs_btnbox.accepted.connect(Preferences.accept)
        self.prefs_btnbox.rejected.connect(Preferences.reject)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Preferences"))
        self.gbox_startup.setTitle(_translate("Preferences", "Startup"))
        self.cbox_loadlastprofile.setText(_translate("Preferences", "Load most recent profile on start"))
        self.gbox_paths.setTitle(_translate("Preferences", "Default Paths"))
        self.btn_choosedir_skyrim.setToolTip(_translate("Preferences", "Open file dialog"))
        self.btn_choosedir_skyrim.setText(_translate("Preferences", "..."))
        self.lbl_skyrim.setToolTip(_translate("Preferences", "Location of Skyrim installation folder"))
        self.lbl_skyrim.setText(_translate("Preferences", "Skyrim"))
        self.btn_choosedir_mods.setToolTip(_translate("Preferences", "Open file dialog"))
        self.btn_choosedir_mods.setText(_translate("Preferences", "..."))
        self.lbl_mods.setToolTip(_translate("Preferences", "Directory where installed mods will be stored"))
        self.lbl_mods.setText(_translate("Preferences", "Mods"))
        self.lbl_vfs.setToolTip(_translate("Preferences", "Path to empty folder to use as virtual-filesystem mount point"))
        self.lbl_vfs.setText(_translate("Preferences", "VFS Mount"))
        self.btn_choosedir_vfs.setToolTip(_translate("Preferences", "Open file dialog"))
        self.btn_choosedir_vfs.setText(_translate("Preferences", "..."))
        self.prefs_tabwidget.setTabText(self.prefs_tabwidget.indexOf(self.tab_general), _translate("Preferences", "General"))
        self.prefs_tabwidget.setTabText(self.prefs_tabwidget.indexOf(self.tab_paths), _translate("Preferences", "Paths"))
        self.prefs_tabwidget.setTabText(self.prefs_tabwidget.indexOf(self.tab_profiles), _translate("Preferences", "Profiles"))

