# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skymodman/interface/designer/ui/preferences_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Preferences_Dialog(object):
    def setupUi(self, Preferences_Dialog):
        Preferences_Dialog.setObjectName("Preferences_Dialog")
        Preferences_Dialog.resize(600, 400)
        self.gridLayout = QtWidgets.QGridLayout(Preferences_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.prefs_btnbox = QtWidgets.QDialogButtonBox(Preferences_Dialog)
        self.prefs_btnbox.setOrientation(QtCore.Qt.Horizontal)
        self.prefs_btnbox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.prefs_btnbox.setObjectName("prefs_btnbox")
        self.gridLayout.addWidget(self.prefs_btnbox, 1, 0, 1, 1)
        self.prefs_tabwidget = QtWidgets.QTabWidget(Preferences_Dialog)
        self.prefs_tabwidget.setObjectName("prefs_tabwidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_general)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbox_general = QtWidgets.QGroupBox(self.tab_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbox_general.sizePolicy().hasHeightForWidth())
        self.gbox_general.setSizePolicy(sizePolicy)
        self.gbox_general.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gbox_general.setObjectName("gbox_general")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbox_general)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self._gbox_startup = QtWidgets.QGroupBox(self.gbox_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._gbox_startup.sizePolicy().hasHeightForWidth())
        self._gbox_startup.setSizePolicy(sizePolicy)
        self._gbox_startup.setTitle("")
        self._gbox_startup.setFlat(True)
        self._gbox_startup.setObjectName("_gbox_startup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self._gbox_startup)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._lbl_startup = QtWidgets.QLabel(self._gbox_startup)
        self._lbl_startup.setObjectName("_lbl_startup")
        self.verticalLayout_2.addWidget(self._lbl_startup)
        self.rad_load_last_profile = QtWidgets.QRadioButton(self._gbox_startup)
        self.rad_load_last_profile.setObjectName("rad_load_last_profile")
        self.verticalLayout_2.addWidget(self.rad_load_last_profile)
        self.rad_load_default_profile = QtWidgets.QRadioButton(self._gbox_startup)
        self.rad_load_default_profile.setObjectName("rad_load_default_profile")
        self.verticalLayout_2.addWidget(self.rad_load_default_profile)
        self.rad_load_no_profile = QtWidgets.QRadioButton(self._gbox_startup)
        self.rad_load_no_profile.setObjectName("rad_load_no_profile")
        self.verticalLayout_2.addWidget(self.rad_load_no_profile)
        self.gridLayout_5.addWidget(self._gbox_startup, 0, 1, 2, 1)
        self._gbox_window = QtWidgets.QGroupBox(self.gbox_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._gbox_window.sizePolicy().hasHeightForWidth())
        self._gbox_window.setSizePolicy(sizePolicy)
        self._gbox_window.setTitle("")
        self._gbox_window.setFlat(True)
        self._gbox_window.setObjectName("_gbox_window")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self._gbox_window)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cbox_restore_size = QtWidgets.QCheckBox(self._gbox_window)
        self.cbox_restore_size.setChecked(True)
        self.cbox_restore_size.setObjectName("cbox_restore_size")
        self.verticalLayout_3.addWidget(self.cbox_restore_size)
        self.cbox_restore_pos = QtWidgets.QCheckBox(self._gbox_window)
        self.cbox_restore_pos.setChecked(True)
        self.cbox_restore_pos.setObjectName("cbox_restore_pos")
        self.verticalLayout_3.addWidget(self.cbox_restore_pos)
        self.gridLayout_5.addWidget(self._gbox_window, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.gbox_general)
        self.gbox_paths = QtWidgets.QGroupBox(self.tab_general)
        self.gbox_paths.setObjectName("gbox_paths")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbox_paths)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_choosedir_skyrim = QtWidgets.QToolButton(self.gbox_paths)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_choosedir_skyrim.setIcon(icon)
        self.btn_choosedir_skyrim.setObjectName("btn_choosedir_skyrim")
        self.gridLayout_2.addWidget(self.btn_choosedir_skyrim, 0, 2, 1, 1)
        self.le_dirskyrim = QtWidgets.QLineEdit(self.gbox_paths)
        self.le_dirskyrim.setObjectName("le_dirskyrim")
        self.gridLayout_2.addWidget(self.le_dirskyrim, 0, 1, 1, 1)
        self.le_dirmods = QtWidgets.QLineEdit(self.gbox_paths)
        self.le_dirmods.setObjectName("le_dirmods")
        self.gridLayout_2.addWidget(self.le_dirmods, 1, 1, 1, 1)
        self.lbl_skyrim = QtWidgets.QLabel(self.gbox_paths)
        self.lbl_skyrim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_skyrim.setObjectName("lbl_skyrim")
        self.gridLayout_2.addWidget(self.lbl_skyrim, 0, 0, 1, 1)
        self.btn_choosedir_mods = QtWidgets.QToolButton(self.gbox_paths)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_choosedir_mods.setIcon(icon)
        self.btn_choosedir_mods.setObjectName("btn_choosedir_mods")
        self.gridLayout_2.addWidget(self.btn_choosedir_mods, 1, 2, 1, 1)
        self.lbl_mods = QtWidgets.QLabel(self.gbox_paths)
        self.lbl_mods.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mods.setObjectName("lbl_mods")
        self.gridLayout_2.addWidget(self.lbl_mods, 1, 0, 1, 1)
        self.lbl_vfs = QtWidgets.QLabel(self.gbox_paths)
        self.lbl_vfs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_vfs.setObjectName("lbl_vfs")
        self.gridLayout_2.addWidget(self.lbl_vfs, 2, 0, 1, 1)
        self.le_dirvfs = QtWidgets.QLineEdit(self.gbox_paths)
        self.le_dirvfs.setObjectName("le_dirvfs")
        self.gridLayout_2.addWidget(self.le_dirvfs, 2, 1, 1, 1)
        self.btn_choosedir_vfs = QtWidgets.QToolButton(self.gbox_paths)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_choosedir_vfs.setIcon(icon)
        self.btn_choosedir_vfs.setObjectName("btn_choosedir_vfs")
        self.gridLayout_2.addWidget(self.btn_choosedir_vfs, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.gbox_paths)
        self.prefs_tabwidget.addTab(self.tab_general, "")
        self.tab_profiles = QtWidgets.QWidget()
        self.tab_profiles.setObjectName("tab_profiles")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_profiles)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gbox_overrides = QtWidgets.QGroupBox(self.tab_profiles)
        self.gbox_overrides.setObjectName("gbox_overrides")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbox_overrides)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.le_skydir_override = QtWidgets.QLineEdit(self.gbox_overrides)
        self.le_skydir_override.setEnabled(False)
        self.le_skydir_override.setObjectName("le_skydir_override")
        self.gridLayout_4.addWidget(self.le_skydir_override, 0, 1, 1, 1)
        self.btn_skydir_override = QtWidgets.QToolButton(self.gbox_overrides)
        self.btn_skydir_override.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_skydir_override.setIcon(icon)
        self.btn_skydir_override.setObjectName("btn_skydir_override")
        self.gridLayout_4.addWidget(self.btn_skydir_override, 0, 2, 1, 1)
        self.le_moddir_override = QtWidgets.QLineEdit(self.gbox_overrides)
        self.le_moddir_override.setEnabled(False)
        self.le_moddir_override.setObjectName("le_moddir_override")
        self.gridLayout_4.addWidget(self.le_moddir_override, 1, 1, 1, 1)
        self.btn_moddir_override = QtWidgets.QToolButton(self.gbox_overrides)
        self.btn_moddir_override.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_moddir_override.setIcon(icon)
        self.btn_moddir_override.setObjectName("btn_moddir_override")
        self.gridLayout_4.addWidget(self.btn_moddir_override, 1, 2, 1, 1)
        self.le_vfsdir_override = QtWidgets.QLineEdit(self.gbox_overrides)
        self.le_vfsdir_override.setEnabled(False)
        self.le_vfsdir_override.setObjectName("le_vfsdir_override")
        self.gridLayout_4.addWidget(self.le_vfsdir_override, 2, 1, 1, 1)
        self.btn_vfsdir_override = QtWidgets.QToolButton(self.gbox_overrides)
        self.btn_vfsdir_override.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btn_vfsdir_override.setIcon(icon)
        self.btn_vfsdir_override.setObjectName("btn_vfsdir_override")
        self.gridLayout_4.addWidget(self.btn_vfsdir_override, 2, 2, 1, 1)
        self.btn_enable_skydir_override = QtWidgets.QPushButton(self.gbox_overrides)
        self.btn_enable_skydir_override.setCheckable(True)
        self.btn_enable_skydir_override.setAutoDefault(False)
        self.btn_enable_skydir_override.setFlat(False)
        self.btn_enable_skydir_override.setObjectName("btn_enable_skydir_override")
        self.gridLayout_4.addWidget(self.btn_enable_skydir_override, 0, 0, 1, 1)
        self.btn_enable_vfsdir_override = QtWidgets.QPushButton(self.gbox_overrides)
        self.btn_enable_vfsdir_override.setCheckable(True)
        self.btn_enable_vfsdir_override.setAutoDefault(False)
        self.btn_enable_vfsdir_override.setObjectName("btn_enable_vfsdir_override")
        self.gridLayout_4.addWidget(self.btn_enable_vfsdir_override, 2, 0, 1, 1)
        self.btn_enable_moddir_override = QtWidgets.QPushButton(self.gbox_overrides)
        self.btn_enable_moddir_override.setCheckable(True)
        self.btn_enable_moddir_override.setAutoDefault(False)
        self.btn_enable_moddir_override.setObjectName("btn_enable_moddir_override")
        self.gridLayout_4.addWidget(self.btn_enable_moddir_override, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gbox_overrides, 1, 0, 1, 4)
        self.combo_profiles = QtWidgets.QComboBox(self.tab_profiles)
        self.combo_profiles.setObjectName("combo_profiles")
        self.gridLayout_3.addWidget(self.combo_profiles, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_profiles)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.cbox_default = QtWidgets.QCheckBox(self.tab_profiles)
        self.cbox_default.setObjectName("cbox_default")
        self.gridLayout_3.addWidget(self.cbox_default, 0, 2, 1, 1)
        self.prefs_tabwidget.addTab(self.tab_profiles, "")
        self.gridLayout.addWidget(self.prefs_tabwidget, 0, 0, 1, 1)

        self.retranslateUi(Preferences_Dialog)
        self.prefs_tabwidget.setCurrentIndex(0)
        self.prefs_btnbox.accepted.connect(Preferences_Dialog.accept)
        self.prefs_btnbox.rejected.connect(Preferences_Dialog.reject)
        self.btn_enable_skydir_override.toggled['bool'].connect(self.le_skydir_override.setEnabled)
        self.btn_enable_skydir_override.toggled['bool'].connect(self.btn_skydir_override.setEnabled)
        self.btn_enable_moddir_override.toggled['bool'].connect(self.le_moddir_override.setEnabled)
        self.btn_enable_moddir_override.toggled['bool'].connect(self.btn_moddir_override.setEnabled)
        self.btn_enable_vfsdir_override.toggled['bool'].connect(self.le_vfsdir_override.setEnabled)
        self.btn_enable_vfsdir_override.toggled['bool'].connect(self.btn_vfsdir_override.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Preferences_Dialog)

    def retranslateUi(self, Preferences_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Preferences_Dialog.setWindowTitle(_translate("Preferences_Dialog", "Preferences"))
        self.gbox_general.setTitle(_translate("Preferences_Dialog", "General"))
        self._lbl_startup.setText(_translate("Preferences_Dialog", "On start, load..."))
        self.rad_load_last_profile.setToolTip(_translate("Preferences_Dialog", "The active profile at last exit"))
        self.rad_load_last_profile.setText(_translate("Preferences_Dialog", "Mos&t recent profile"))
        self.rad_load_default_profile.setToolTip(_translate("Preferences_Dialog", "Profile marked as Default on the Profiles tab"))
        self.rad_load_default_profile.setText(_translate("Preferences_Dialog", "&Default profile"))
        self.rad_load_no_profile.setToolTip(_translate("Preferences_Dialog", "Don\'t load any profile data"))
        self.rad_load_no_profile.setText(_translate("Preferences_Dialog", "None"))
        self.cbox_restore_size.setText(_translate("Preferences_Dialog", "Remember window &size"))
        self.cbox_restore_pos.setText(_translate("Preferences_Dialog", "Remember window posi&tion"))
        self.gbox_paths.setTitle(_translate("Preferences_Dialog", "Default Paths"))
        self.btn_choosedir_skyrim.setToolTip(_translate("Preferences_Dialog", "Open file dialog"))
        self.btn_choosedir_skyrim.setText(_translate("Preferences_Dialog", "..."))
        self.lbl_skyrim.setToolTip(_translate("Preferences_Dialog", "Location of Skyrim installation folder"))
        self.lbl_skyrim.setText(_translate("Preferences_Dialog", "Skyrim"))
        self.btn_choosedir_mods.setToolTip(_translate("Preferences_Dialog", "Open file dialog"))
        self.btn_choosedir_mods.setText(_translate("Preferences_Dialog", "..."))
        self.lbl_mods.setToolTip(_translate("Preferences_Dialog", "Directory where installed mods will be stored"))
        self.lbl_mods.setText(_translate("Preferences_Dialog", "Mods"))
        self.lbl_vfs.setToolTip(_translate("Preferences_Dialog", "Path to empty folder to use as virtual-filesystem mount point"))
        self.lbl_vfs.setText(_translate("Preferences_Dialog", "VFS Mount"))
        self.btn_choosedir_vfs.setToolTip(_translate("Preferences_Dialog", "Open file dialog"))
        self.btn_choosedir_vfs.setText(_translate("Preferences_Dialog", "..."))
        self.prefs_tabwidget.setTabText(self.prefs_tabwidget.indexOf(self.tab_general), _translate("Preferences_Dialog", "General"))
        self.gbox_overrides.setToolTip(_translate("Preferences_Dialog", "Override the default paths"))
        self.gbox_overrides.setTitle(_translate("Preferences_Dialog", "Path Overrides"))
        self.btn_skydir_override.setToolTip(_translate("Preferences_Dialog", "Open file dialog"))
        self.btn_skydir_override.setText(_translate("Preferences_Dialog", "..."))
        self.btn_moddir_override.setToolTip(_translate("Preferences_Dialog", "Open file dialog"))
        self.btn_moddir_override.setText(_translate("Preferences_Dialog", "..."))
        self.btn_vfsdir_override.setToolTip(_translate("Preferences_Dialog", "Open file dialog"))
        self.btn_vfsdir_override.setText(_translate("Preferences_Dialog", "..."))
        self.btn_enable_skydir_override.setToolTip(_translate("Preferences_Dialog", "Press to enable this override"))
        self.btn_enable_skydir_override.setText(_translate("Preferences_Dialog", "Skyrim"))
        self.btn_enable_vfsdir_override.setToolTip(_translate("Preferences_Dialog", "Press to enable this override"))
        self.btn_enable_vfsdir_override.setText(_translate("Preferences_Dialog", "VFS Mount"))
        self.btn_enable_moddir_override.setToolTip(_translate("Preferences_Dialog", "Press to enable this override"))
        self.btn_enable_moddir_override.setText(_translate("Preferences_Dialog", "Mods"))
        self.groupBox.setTitle(_translate("Preferences_Dialog", "Path Overrides"))
        self.cbox_default.setToolTip(_translate("Preferences_Dialog", "Default profile"))
        self.prefs_tabwidget.setTabText(self.prefs_tabwidget.indexOf(self.tab_profiles), _translate("Preferences_Dialog", "Profiles"))

